language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - gcc libffi-dev libldap2-dev libsasl2-dev libssl-dev python-dev
install:
  # Build/test dependencies
  - python setup.py install
script:
  - python setup.py test
